Repository all-of-us/data-browser, pull requests merged in 2019-04, with the labels that each got.

#188 [risk=no][DB-396] show more bug
  public-ui/src/app/views/ehr-view/ehr-view.component.html
Labels: needs review

#195 [DB-457] [risk=no] adding tooltip to questions that have multiple answers
  public-ui/src/app/data-browser/concept-charts/concept-charts.component.ts
  public-ui/src/app/utils/db-config.service.ts
  public-ui/src/app/utils/tooltip.service.ts
  public-ui/src/app/views/survey-view/survey-view.component.html
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: needs review

#197 [risk=no][DB-453]
  public-ui/src/app/utils/tooltip.service.ts
Labels: needs review

#198 [risk=no][DB-382]
  public-ui/src/app/views/ehr-view/ehr-view.component.ts
Labels: needs review

#179 [Db-408][risk=low] Criteria stratum roll up counts
  public-api/config/cdr_versions_stable.json
  public-api/config/cdr_versions_staging.json
  public-api/config/cdr_versions_test.json
  public-api/db-cdr/generate-cdr/bq-schemas/criteria_stratum.json
  public-api/db-cdr/generate-cdr/csv/filter_conditions.csv
  public-api/db-cdr/generate-cdr/generate_criteria_stratum.sh
  public-api/db-cdr/generate-cdr/make-bq-data-dump.sh
  public-api/db-cdr/generate-cdr/make-bq-data.sh
Labels: needs review

#200 [DB-444] [risk=no] cdr info on the landing page
  common-api/src/main/resources/common_api.yaml
  public-api/src/main/java/org/pmiops/workbench/publicapi/DataBrowserController.java
  public-api/src/main/resources/public-api.yaml
  public-api/src/test/java/org/pmiops/workbench/cdr/DataBrowserControllerTest.java
  public-ui/src/app/views/quick-search/quick-search.component.css
  public-ui/src/app/views/quick-search/quick-search.component.html
  public-ui/src/app/views/quick-search/quick-search.component.ts
Labels: needs review

#202 [DB-399] [risk=no] flipping y axis
  public-ui/src/app/data-browser/chart/chart.component.ts
Labels: needs review

#204 [DB-351] [risk=no] select the searched pm
  public-api/db-cdr/generate-cdr/csv/unit_map.csv
  public-ui/src/app/views/pm/pm.component.ts
  public-ui/src/app/views/quick-search/quick-search.component.html
  public-ui/src/app/views/quick-search/quick-search.component.ts
Labels: needs review

#203 [DB-416] [risk=no] aligning see more together with the text
  public-ui/src/app/views/ehr-view/ehr-view.component.css
  public-ui/src/app/views/ehr-view/ehr-view.component.html
Labels: needs review

#215 [DB-494] [risk=no] Make whole survey answer row clickable for sub level answers
  public-ui/src/app/views/survey-view/survey-view.component.html
Labels: needs review

#216 [DB-444] suggestion:
  public-ui/src/app/views/quick-search/quick-search.component.html
Labels: suggestion

#217 [DB-492] [risk=no] display gender labels only if the results.length > 0
  public-ui/src/app/data-browser/concept-charts/concept-charts.component.html
  public-ui/src/app/views/ehr-view/ehr-view.component.html
Labels: needs review

#219 [risk=no][DB-458]urls match titles
  public-ui/src/app/utils/db-config.service.ts
  public-ui/src/app/views/breadcrumb/breadcrumb.component.ts
  public-ui/src/app/views/ehr-view/ehr-view.component.ts
  public-ui/src/app/views/quick-search/quick-search.component.html
  public-ui/src/app/views/quick-search/quick-search.component.ts
Labels: needs review

#201 [risk=no] cdr version update in prod
  public-api/config/cdr_versions_prod.json
Labels: needs review

#234 [DB-454] [risk=no] Removing race/ethnicity tab on the graphs
  public-ui/src/app/views/db-header/db-header.component.html
  public-ui/src/app/views/ehr-view/ehr-view.component.ts
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: high priority, needs review

#236 [DB-523] [risk=no] Removing branching logic for race/ ethnicity question in basics.
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: high priority, needs review

#242 [DB-523] [risk=no] Removing branching logic of rest of answers as it is
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: high priority, needs review

#237 [risk=no][DB-331]Header/footer-links
  public-ui/src/app/views/db-header/db-header.component.html
  public-ui/src/app/views/db-header/db-header.component.ts
  public-ui/src/app/views/quick-search/quick-search.component.html
  public-ui/src/app/views/quick-search/quick-search.component.ts
  public-ui/src/assets/db-images/allofus_research-hub_white.png
  public-ui/src/assets/db-images/nih_allofus_white.png
  public-ui/src/index.html
Labels: needs review

#244 [risk=no][DB-284]Scroll only when window is small + bold highlight
  public-ui/src/app/highlight-search/highlight-search.component.css
  public-ui/src/app/views/ehr-view/ehr-view.component.css
  public-ui/src/app/views/pm/pm.component.css
  public-ui/src/app/views/survey-view/survey-view.component.css
Labels: needs review

#245 [DB-526] [risk=low] updating help text on q2
  public-ui/src/app/utils/tooltip.service.ts
  public-ui/src/app/views/survey-view/survey-view.component.html
Labels: high priority, needs review

#248 [DB-361] [risk=no] removing search url changes
  public-ui/src/app/views/ehr-view/ehr-view.component.ts
  public-ui/src/app/views/quick-search/quick-search.component.html
  public-ui/src/app/views/quick-search/quick-search.component.ts
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: high priority, needs review

#249 [risk=no][DB-498]remove unneeded icon
  public-ui/src/app/views/survey-view/survey-view.component.html
Labels: needs review

#251 [DB-528] [risk=low] Fix the query that adds non-present breakdown counts
  public-api/db-cdr/generate-cdr/make-bq-data.sh
  public-ui/src/app/components/source-tree/source-tree.component.ts
Labels: high priority, needs review

#252 [risk=no][DB-502]source-tree-bugs
  public-ui/src/app/components/db-spinner/db-spinner.component.html
  public-ui/src/app/components/recursive-tree/recursive-tree.component.css
  public-ui/src/app/components/recursive-tree/recursive-tree.component.html
  public-ui/src/app/components/recursive-tree/recursive-tree.component.ts
  public-ui/src/app/components/source-tree/source-tree.component.ts
Labels: high priority, needs review

#255 [DB-240] [risk=no] making the whole box clickable
  public-ui/src/app/views/quick-search/quick-search.component.html
Labels: needs review

#261 [risk=no] prod cdr version update
  public-api/config/cdr_versions_prod.json
Labels: high priority, needs review

#262 [DB-536] [risk=no] tooltip for q2 rolled into other
  public-ui/src/app/utils/tooltip.service.ts
  public-ui/src/app/views/survey-view/survey-view.component.html
Labels: high priority, needs review

#264 [DB-538] [risk=no] matching underlined name on survey charts
  public-ui/src/app/views/survey-chart/survey-chart.component.css
  public-ui/src/app/views/survey-chart/survey-chart.component.html
  public-ui/src/app/views/survey-chart/survey-chart.component.ts
Labels: needs review

#266 [risk=no][DB-548]fixing spelling
  public-ui/src/app/views/quick-search/quick-search.component.html
Labels: needs review

#265 [DB-540] [risk=low] Removing duplicate age bin data
  public-api/config/cdr_versions_stable.json
  public-api/config/cdr_versions_staging.json
  public-api/config/cdr_versions_test.json
  public-api/db-cdr/generate-cdr/make-bq-data.sh
  public-api/db-cdr/generate-cdr/run-achilles-queries.sh
Labels: needs review

#271 [DB-557] [risk=no] Change the biological sex label in charts
  public-ui/src/app/data-browser/chart/chart.component.ts
  public-ui/src/app/data-browser/concept-charts/concept-charts.component.html
  public-ui/src/app/utils/enum-defs.ts
  public-ui/src/app/views/ehr-view/ehr-view.component.ts
  public-ui/src/app/views/quick-search/quick-search.component.html
  public-ui/src/app/views/survey-chart/survey-chart.component.ts
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: needs review

#272 [DB-570] [risk=low] Update data query
  public-api/config/cdr_versions_stable.json
  public-api/config/cdr_versions_staging.json
  public-api/config/cdr_versions_test.json
  public-api/db-cdr/generate-cdr/csv/achilles_analysis.csv
  public-api/db-cdr/generate-cdr/make-bq-data.sh
  public-api/db-cdr/generate-cdr/make-bq-public-data.sh
Labels: needs review

#286 [DB-560] [risk=no] count the drug concepts with count > 0
  common-api/src/main/java/org/pmiops/workbench/cdr/dao/ConceptDao.java
Labels: high priority, needs review

#290 [risk=no][DB-554]Zendesk Widget
  public-ui/src/app/components/beta-bar/beta-bar.component.css
  public-ui/src/app/components/beta-bar/beta-bar.component.html
  public-ui/src/index.html
Labels: needs review

#289 [DB-551] [risk=no] making did not answer count 20 if less than 20
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: high priority, needs review

#292 [risk=no]ui detail
  public-ui/src/app/styles/page.css
  public-ui/src/app/views/ehr-view/ehr-view.component.ts
  public-ui/src/index.html
Labels: needs review

#306 [DB-578] [risk=no] Survey chart conversion
  public-ui/src/app/data-browser/chart/chart.component.ts
  public-ui/src/app/highlight-search/highlight-search.component.ts
  public-ui/src/app/utils/db-config.service.ts
  public-ui/src/app/views/survey-view/survey-view.component.ts
Labels: high priority, needs review
